### ISSUE TITLE
Do you know about `lc`?

### ISSUE THREAD

**Issue by c-blake** [madprops/lq#1]
You may find some if its ideas interesting:
    https://github.com/c-blake/lc

(The dircount feature you have is possible with my external command extensions, but it would be better to follow up on my extensions via shared libraries idea.)

Possibly also of interest is the closely related https://github.com/c-blake/procs

If you did, or even if you didn't know, feel free to close this issue.  It's mostly the easiest way for me to make you aware of something you might be interested in.

**Comment by madprops** [comment]
Looks cool. I'll leave this open to let others find it.

**Comment by llagerlof** [comment]
This isn't an issue. Should not to stay open. I have an idea. I know, the "idea" guy... ;-) 

If the dev wants to let other people find other related tools, why not to create a section in README, like "Related Tools" or something like that?

Or create a wiki page?
