### ISSUE TITLE
A bit of grid/table conformity, less whitespace, little indent to snippets

### ISSUE THREAD

**Issue by lf-araujo** [madprops/lq#10]
First of all, congratulations, this tool is excellent as it is. However, I wanted to make three suggestions:

1. allow for a --fluid2 flag that removes the extra lines between files and directories but keeps the titles (the opposite to --fluid behavior).

2. try a better algorithm for making the files and directories align better to a table grid, it still bounces quite a bit, check the comparison to ls below:

![image](https://user-images.githubusercontent.com/10139950/72025879-5010a380-3258-11ea-8371-c5db1f12120a.png)

3. a bit of indentation, perhaps two chars to the left can improve significantly readability of directories with numerous text files:

![image](https://user-images.githubusercontent.com/10139950/72025555-42a6e980-3257-11ea-99ab-b512368b778f.png)

Thanks again

**Comment by madprops** [comment]
Hey, thank you for the feedback. I made some changes towards suggestions 1 and 3. 

This the new --fluid2 or -U mode:

![screenshot_1](https://user-images.githubusercontent.com/206498/72098680-99a6d000-32e4-11ea-9b5a-2bda303a2901.png)

![screenshot_3](https://user-images.githubusercontent.com/206498/72099038-5d27a400-32e5-11ea-9f9f-dc7511ad3e58.png)

Also added 2 spaces before each snippet line:

![screenshot_2](https://user-images.githubusercontent.com/206498/72098765-c35ff700-32e4-11ea-81a7-3406d03176d3.png)

About #2, I haven't figured out how to do it properly, so I've decided not to provide tabular information like ls unless I find a library that makes this easy.

**Comment by lf-araujo** [comment]
Thank you very much for accepting some of my suggestions!

This looks very nice, will update immediately. Thanks!


-- 
Honorary Clinical Lecturer | Department of Psychiatry | The University 
of Melbourne
Post Doc | Center of Data and Knowledge Integration for Health (CIDACS) 
| Salvador | Brazil
p: +55 71 988477207 | http://go.unimelb.edu.au/y5yr On qui, jan 9, 2020
