### ISSUE TITLE
Ignore specific directories

### ISSUE THREAD

**Issue by llagerlof** [madprops/lq#2]
I nice feature for developers would be the possibility to ignore specific directories.

**1.** Ignore directories using a cli option. eg:
```
$ lq --tree --ignore-dirs=.git;.svn;.templates_c
```

**2.** Ignore by default a list of directories using a config file. eg:
**~/.lq.config**
```
[ignore-dirs]
    .git
    .svn
    .templates_c
```

**Comment by madprops** [comment]
Just added that.
This is from the updated README:

## Exclude

Excluding files affects modes like --tree

It can be specified multiple times.

i.e myprogram --exclude=bigDir -e=.git -e=target
 
It is checked as:

```
full_path.contains(&"/{e}/")
```

So if ".git" is excluded then

it will match whatever contains `/.git/` for instance,

and not show its content in the tree view.

## Config File
In Linux a config is placed in ~/config/lq/lq.conf

It uses the TOML format.

Right now it has a section to add directories to exclude.

It looks like this:

```
exclude = [
  ".git",
  ".svn"
]
```
