### ISSUE TITLE
"lq --tree" raises exception (IOError)

### ISSUE THREAD

**Issue by llagerlof** [madprops/lq#3]
I downloaded the last version of bin/lq-release-linux (bd5fcab).
I tried to run the command `lq --tree` but an error was raised:
```
parsetoml.nim(1207)      parseStream
Error: unhandled exception: Unable to read from the stream created from: "/home/user1/.config/lq/lq.conf", possibly a missing file [IOError]
```

**Comment by llagerlof** [comment]
I tried to manually create the ~/.config/lq/lq.conf with the contents below:
```
exclude = [
  ".git",
  ".svn",
  "node_modules",
  "templates_c"
]
```
But now another error is raised when I run `lq --tree`:
```
tables.nim(264)          []
Error: unhandled exception: key not found: colors [KeyError]
```

**Comment by madprops** [comment]
Yep. The recommended way is to run the install_linux.sh script (or buildinstall_linux.sh if you have the nim compiler and want to compile). Or copy the file with copy_config.sh. You only added part of the config file there.

**Comment by madprops** [comment]
Also just removed some debugging echo (print) that made it to that release which appeared if you used --tree with --filter.

**Comment by llagerlof** [comment]
Wow. I missed the new option `filtermatch` in config file. Thank you.
