### ISSUE TITLE
Strange behaviour hiding folders when using option "--tree"

### ISSUE THREAD

**Issue by llagerlof** [madprops/lq#4]
Playing with the new feature --tree, I found two problems. Let's see it. I created the following structure:
```
user1234@srv001:~/books$ tree -a
.
├── not_hidden_dir
│   ├── book_lost1.txt
│   └── book_lost2.pdf
├── Science Fiction
│   ├── .arthur_c_clarke
│   │   └── The End of Tomorrow.mobi
│   └── Asimov
│       ├── I, Robot.md
│       └── The Bicentennial Man.doc
└── .unknown
    └── The blob.docx
```
The `lq --tree` gave me the full tree, correctly:

```
.unknown
    The blob.docx

not_hidden_dir
    book_lost1.txt
    book_lost2.pdf

Science Fiction
    .arthur_c_clarke
        The End of Tomorrow.mobi
    Asimov
        I, Robot.md
        The Bicentennial Man.doc
```

The problem starts when I try to hide some dirs. I added to config file:
```
exclude = [
  ".unknown",
  ".arthur_c_clarke"
]
```

And the output turned into this:
```
.unknown
    (Excluded)

not_hidden_dir
    book_lost1.txt
    book_lost2.pdf

Science Fiction
    (Excluded)
```

Looks like the entire `Science Fiction` directory was hidden.

The second problem, maybe related to this one:

I create a directory inside "Science Fiction", named "this_will_be_hidden_from_lq". Created a file inside too.
I added "this_will_be_hidden_from_lq" to the config file.
I removed the ".arthur_c_clarke" from the config file (to not interfere with this test).

When I run lq --tree, this is what I have:

```
.unknown
    The blob.docx

not_hidden_dir
    book_lost1.txt
    book_lost2.pdf

Science Fiction
    .arthur_c_clarke
        The End of Tomorrow.mobi
    Asimov
        I, Robot.md
        The Bicentennial Man.doc
```

The directory "this_will_be_hidden_from_lq" shouldn't appear inside `Science Fiction`? Like:
```
Science Fiction
    .arthur_c_clarke
        The End of Tomorrow.mobi
    Asimov
        I, Robot.md
        The Bicentennial Man.doc
    this_will_be_hidden_from_lq
        (Excluded)
```

**Comment by madprops** [comment]
Thank you for the report. I played around with the dir structure you used. And indeed there were some problems. I ended up making this modification:

```nim
if excluded:
  if file.kind == pcFile or 
  file.kind == pcLinkToFile:
    msg = "(Excluded)"
    break filesblock   
```

And both problems seem to be gone.

**Comment by madprops** [comment]
Further modifications:

```nim
for e in conf().exclude:
  let rs = re(&"/{e}/.*")
  if full_path.find(rs).isSome and conf().path.find(rs).isNone:
    msg = "(Excluded)"
    break filesblock  
```

**Comment by madprops** [comment]
Added pipes/lines to the tree view. The color of the pipes is also configurable.

![](http://i.imgur.com/NS2VS6t.jpg)

**Comment by llagerlof** [comment]
I tested here the new version. Everything mentioned in this issue is working. Fantastic!
