### ISSUE TITLE
Add color option to executable files

### ISSUE THREAD

**Issue by llagerlof** [madprops/lq#5]
In configuration file we have the option ```files``` inside the section ```[colors]``` to set the color os files. Would be nice, even useful, if we have an option to choose the color of executable files.

**Comment by madprops** [comment]
Added options for coloring executables, for normal files and link files.
The default is just the same color (white or green) but with underscores.
Also made some refactoring internally to store all colors in a table.

```
# File items
# files = ""

# Executable File items
# exefiles = "underscore"

# File Link items
# filelinks = "green"

# Executable File Link items
# exefilelinks = "underscore green"
```

**Comment by madprops** [comment]
Changed the default to be just bright/bold, to be less cluttered.

**Comment by madprops** [comment]
Made a big modification. Now files can be categorized as executables or not executables.

This allows different display layouts like image below. And different prefixes like [E] and [e].

These now have the same color as files and links, no bright or anything. This can still be customized of course.

![](http://i.imgur.com/xlSX9M8.jpg)

**Comment by madprops** [comment]
Further changes. Lots of color modifications.

**Comment by llagerlof** [comment]
Beautiful improvement. I tested the new features and looks very good now. Thank you!
