### ISSUE TITLE
File and directory are being sorted differently by modification date (lq -d)

### ISSUE THREAD

**Issue by llagerlof** [madprops/lq#6]
The `lq -d` behaves different for each type of object:

- The directories are sorted in ascending order. 
- The files are sorted in descending order.
- The executables are not being sorted.
- Links always are at the end of listing of its respective category (I am not sure if this is default or an issue).

**Comment by llagerlof** [comment]
Would be possible to add an option to choose between ascending or descendig order?

**Comment by madprops** [comment]
Made some modifications on how lists are stored internally. Now links don't have their own list, they all go inside dirs, files, or execs. This makes things a bit easier to work with, and now they can be sorted (i.e links are not always at the end).

Fixed executables not being sorted, and generally changed how sorting works internally.

Added a --reverse-sort (-R) option to change the direction of sorting.

Couldn't see what you meant about directories being sorted differently, running some tests they seem to follow the same rules as files.

Thanks btw

**Comment by madprops** [comment]
Added some new flags to show dates.

--date (-k) Show how many days ago files were modified.
--dirdate (-K) Same but with directories.

Changed dsize to dirsize. size and dirsize are now -z -Z

![](http://i.imgur.com/zteReJV.jpg)

**Comment by madprops** [comment]
Btw added a new mode: Snippets

![](http://i.imgur.com/860r4Fp.jpg)

**Comment by llagerlof** [comment]
Just a question. When sorting by date, the program consider the time too?

**Comment by madprops** [comment]
When sorting it uses the last modification date. In the case of directories it checks every file inside to find the most recent date.

When showing the date, it does use the current time to compare.

**Comment by llagerlof** [comment]
I am having a strange behaviour, but it's inconsistent depending on directory I am in.

I created right now 3 new files (new1, new2, new3) (in that order) and 3 new directories (dnew1, dnew2, dnew3) (in that order). Created 3 new executables too (exec1, exec2, exec3) (in that order).
Look how they appear to me when using `lq -d`:

```
Directories (9)

  .unknown  ScyFy  Science Fiction  not_hidden_dir  parsec  light  dnew3  dnew2  dnew1

Files (13)

  new3  new2  new1  .hidden  hide.txt  sound  w  y  z  bbb  scri.sh  commonfile.txt

  the-blob.docx

Executables (9)

  exec3  exec2  exec1  water  easy  x  linkexec1  ccc  aaa.txt
```

The above new objects has these modification dates:
```
Dec  6 10:40  new1
Dec  6 10:41  new2
Dec  6 10:42  new3

Dec  6 10:40  dnew1
Dec  6 10:41  dnew2
Dec  6 10:42  dnew3

Dec  6 10:40  exec1
Dec  6 10:41  exec2
Dec  6 10:42  exec3
```

Oddly enough, I create an all-new directory outside and made the same experiment. Look at the result:
```
Directories (3)

  dir3  dir2  dir1

Files (3)

  file3  file2  file1

Executables (3)

  exec3  exec2  exec1
```

And its modification dates:
```
Dec  6 10:32 dir1
Dec  6 10:33 dir2
Dec  6 10:34 dir3

Dec  6 10:32 exec1
Dec  6 10:33 exec2
Dec  6 10:34 exec3

Dec  6 10:32 file1
Dec  6 10:33 file2
Dec  6 10:34 file3
```

So, for some strange reason, in the first test (books) the directory sort order is ~~reversed~~ strange.  Doesn't even is reversed because `dnew3` would be the last one.

I could not replicate the problem outside this directory, so if you could not too, I presume this issue can be closed.

**Comment by madprops** [comment]
Good catch. I found the problem.

As you can see it was detecting the default date. This is because they don't have files inside.

![](http://i.imgur.com/47cV7Xa.jpg)

What I did was, if no files, then check the date of the dir itself.

![](http://i.imgur.com/WV4Uiyf.jpg)

**Comment by llagerlof** [comment]
Perfection.
